### ISSUE TITLE
Build error with Centos 7.1 and HHVM 3.7.0

### ISSUE THREAD

**Issue by no1youknowz** [PocketRent/hhvm-pgsql#90]
I'm doing this:

    git clone https://github.com/PocketRent/hhvm-pgsql.git hhvm-ext-pgsql
    cd hhvm-ext-pgsql
    git checkout 3.7.0
    git checkout -b 3.7.0

    /usr/bin/hphpize
    cmake .
    make

    -- The C compiler identification is GNU 4.8.3
    -- The CXX compiler identification is GNU 4.8.3
    -- The ASM compiler identification is GNU
    -- Found assembler: /bin/cc
    -- Check for working C compiler: /bin/cc
    -- Check for working C compiler: /bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working CXX compiler: /bin/c++
    -- Check for working CXX compiler: /bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Configuring for HHVM API version 20150212
    -- pgSQL Include dir: /usr/include
    -- libpq library: /usr/lib64/libpq.so
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql
    + make
    Scanning dependencies of target pgsql
    [ 25%] Building CXX object CMakeFiles/pgsql.dir/pgsql.cpp.o
    [ 50%] Building CXX object CMakeFiles/pgsql.dir/pdo_pgsql_statement.cpp.o
    In file included from /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pdo_pgsql_resource.h:4:0,
                     from /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pdo_pgsql_statement.cpp:1:
    /usr/include/hphp/runtime/ext/pdo_driver.h:242:5: warning: 'virtual HPHP::SmartPtr<HPHP::PDOResource> HPHP::PDODriver::createResourceImpl(const sp_PDOConnection&)' was hidden [-Woverloaded-virtual]
         createResourceImpl(const sp_PDOConnection& conn) = 0;
         ^
    In file included from /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pdo_pgsql_statement.cpp:4:0:
    /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pdo_pgsql.h:10:35: warning:   by 'virtual HPHP::SmartPtr<HPHP::PDOResource> HPHP::PDOPgSql::createResourceImpl()' [-Woverloaded-virtual]
         virtual SmartPtr<PDOResource> createResourceImpl() override;
                                       ^
    [ 75%] Building CXX object CMakeFiles/pgsql.dir/pdo_pgsql_connection.cpp.o
    In file included from /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pdo_pgsql_connection.h:4:0,
                     from /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pdo_pgsql_connection.cpp:1:
    /usr/include/hphp/runtime/ext/pdo_driver.h:242:5: warning: 'virtual HPHP::SmartPtr<HPHP::PDOResource> HPHP::PDODriver::createResourceImpl(const sp_PDOConnection&)' was hidden [-Woverloaded-virtual]
         createResourceImpl(const sp_PDOConnection& conn) = 0;
         ^
    In file included from /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pdo_pgsql_connection.cpp:4:0:
    /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pdo_pgsql.h:10:35: warning:   by 'virtual HPHP::SmartPtr<HPHP::PDOResource> HPHP::PDOPgSql::createResourceImpl()' [-Woverloaded-virtual]
         virtual SmartPtr<PDOResource> createResourceImpl() override;
                                       ^
    [100%] Building CXX object CMakeFiles/pgsql.dir/pdo_pgsql.cpp.o
    In file included from /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pdo_pgsql.h:5:0,
                     from /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pdo_pgsql.cpp:1:
    /usr/include/hphp/runtime/ext/pdo_driver.h:242:5: warning: 'virtual HPHP::SmartPtr<HPHP::PDOResource> HPHP::PDODriver::createResourceImpl(const sp_PDOConnection&)' was hidden [-Woverloaded-virtual]
         createResourceImpl(const sp_PDOConnection& conn) = 0;
         ^
    In file included from /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pdo_pgsql.cpp:1:0:
    /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pdo_pgsql.h:10:35: warning:   by 'virtual HPHP::SmartPtr<HPHP::PDOResource> HPHP::PDOPgSql::createResourceImpl()' [-Woverloaded-virtual]
         virtual SmartPtr<PDOResource> createResourceImpl() override;
                                       ^
    /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pdo_pgsql.cpp:8:17: error: cannot declare variable 'HPHP::s_pgsql_driver' to be of abstract type 'HPHP::PDOPgSql'
     static PDOPgSql s_pgsql_driver;
                     ^
    In file included from /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pdo_pgsql.cpp:1:0:
    /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pdo_pgsql.h:8:8: note:   because the following virtual functions are pure within 'HPHP::PDOPgSql':
     struct PDOPgSql : public PDODriver {
            ^
    In file included from /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pdo_pgsql.h:5:0,
                     from /root/rpmbuild/BUILD/hhvm-ext-pgsql-1.1.0/hhvm-ext-pgsql/pdo_pgsql.cpp:1:
    /usr/include/hphp/runtime/ext/pdo_driver.h:242:5: note: 	virtual HPHP::SmartPtr<HPHP::PDOResource> HPHP::PDODriver::createResourceImpl(const sp_PDOConnection&)
         createResourceImpl(const sp_PDOConnection& conn) = 0;
         ^
    make[2]: *** [CMakeFiles/pgsql.dir/pdo_pgsql.cpp.o] Error 1
    make[1]: *** [CMakeFiles/pgsql.dir/all] Error 2
    make: *** [all] Error 2
    error: Bad exit status from /var/tmp/rpm-tmp.0P9amq (%build)

    RPM build errors:
        Bad exit status from /var/tmp/rpm-tmp.0P9amq (%build)

**Comment by no1youknowz** [comment]
Hey,

So any movement on this, getting resolved soon?

Thanks

**Comment by no1youknowz** [comment]
Can close this now.  I skipped 3.6.x and 3.7.x.  Builds fine with the latest master (3.8) of hhvm.
