### PR TITLE
Fix build on HHVM 3.8.0

### LINKED ISSUE #86: hhvm-pgsql doesn't build against hhvm 3.8.0
Here's the first of a handful of seemingly related errors:

```

Scanning dependencies of target pgsql
[ 25%] Building CXX object CMakeFiles/pgsql.dir/pgsql.cpp.o
/home/rrh/git-work-2/php_agent/hhvm-pgsql/pgsql.cpp: In static member function ‘static HPHP::{anonymous}::PGSQL* HPHP::{anonymous}::PGSQL::Get(const HPHP::Variant&)’:
/home/rrh/git-work-2/php_agent/hhvm-pgsql/pgsql.cpp:210:67: error: cannot convert ‘HPHP::SmartPtr<HPHP::{anonymous}::PGSQL>’ to ‘HPHP::{anonymous}::PGSQL*’ in initialization
     PGSQL *pgsql = conn_id.toResource().getTyped<PGSQL>(true, true);
                                                                   ^

```

### PR DESCRIPTION
**Pull request by tlevi**
What it says on the tin; fixes #86.

### CODE REVIEW

**Comment by rrh** [comment]
This seems to conflict with the strategy taken in https://github.com/PocketRent/hhvm-pgsql/pull/88

**Comment by simonwelsh** [comment]
Fixed by #89.
